name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker with Arch Linux
      run: |
        docker pull archlinux:latest

    - name: Build in Arch Linux Container
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace archlinux:latest /bin/bash -c "
          pacman -Sy --noconfirm base-devel git make && \
          make
        "

    - name: Create Tarball or Binary
      run: |
        tar -czf myprogram.tar.gz myprogram

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: myprogram-artifact
        path: myprogram.tar.gz
